package org.usfirst.frc.team3019.robot.subsystems;

import org.usfirst.frc.team3019.robot.Robot;

import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class PIDDrive extends PIDSubsystem {

	//instantiate objects used
	NetworkTable table;
	public static double P;
    
    public PIDDrive(double P, double I, double D) {
    
    	super(P,I,D);
    	
    	//retrieve network table put up by TowerTracker jar
    	table = NetworkTable.getTable("TowerTracker");
    	
    	//focus PID info
    	setSetpoint(0);
    	setInputRange(-25, 25);
    	setAbsoluteTolerance(1);
    	setOutputRange(-.7, .7);
    
    }
    
    public void initDefaultCommand() {
    }
 
//DO: sets the correct input to be used for PID Driving 
    protected double returnPIDInput() {
    
    	//input for PID System is the azimuthal ( angle off from center/forward in horizontal aspect)
    	return SmartDashboard.getNumber("azimuth",0);
    
    }
    
//DO: sets correct output to be generated by PID
    protected void usePIDOutput(double output) {
    	
    	//Output of pid to rotate bot towards center/forward
    	Robot.driveTrain.arcadeDrive(0, -output);
    
    }

}