package org.usfirst.frc.team3019.robot.subsystems;

import org.usfirst.frc.team3019.robot.Robot;

import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.networktables.NetworkTable;

public class PIDDriving extends PIDSubsystem {

	// instantiate objects used
	NetworkTable table;
	public static double P;

	public double initialYaw;
	public double initialAzimuth;
	public double deltaYaw;

	/**
	 * 
	 * @param P
	 *            P term for the pid
	 * @param I
	 *            I term for the pid
	 * @param D
	 *            D term for the pid
	 * @param setPoint
	 *            the setpoint for the pid loop
	 */
	public PIDDriving(double P, double I, double D, double setPoint) {

		super(P, I, D);

		// retrieve network table put up by TowerTracker jar
		table = NetworkTable.getTable("TowerTracker");

		setSetpoint(0);
		// setInputRange(-25, 25);
		setAbsoluteTolerance(1);
		setOutputRange(-1, 1);

	}

	public PIDDriving(double P, double I, double D) {
		// TODO Auto-generated constructor stub
		this(P, I, D, 0);
	}

	public void initDefaultCommand() {
	}

	// DO: sets the correct input to be used for PID Driving
	protected double returnPIDInput() {

		// this is what we want to be zero
		// input for PID System is the azimuthal ( angle off from center/forward
		// in horizontal aspect)
		return initialAzimuth + deltaYaw;

	}

	// DO: sets correct output to be generated by PID
	protected void usePIDOutput(double output) {

		// Output of pid to rotate bot towards center/forward
		Robot.driveTrain.arcadeDrive(0, output);

	}

}